AWSTemplateFormatVersion: "2010-09-09"
Description: "Task Management System"

Resources:
  CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: TaskUserPool
    AutoVerifiedAttributes:
      - email
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: TaskIdentityPool
      AllowUnauthenticatedIdentities: false

Outputs:
  UserPoolId:
  Value: !GetAtt CognitoUserPool.UserPoolId
